name: golangci-lint
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42
        skip-pkg-cache: true
        skip-build-cache: true
        skip-go-installation: true
